--- # Variable substitution
- hosts: '{{ myhosts }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  vars:
    myhosts: centos
    gather: yes
    pkg: telnet
  tasks:
  - name: 
    yum:
      name: '{{ pkg }}'
      state: latest
